version: '3.8'

services:
  app:
    container_name: sumo-insight-backend-prod
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: always
